/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ayed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Torus.geometry} material={materials['Material.001']} scale={[1, 1.52, 1]} />
    </group>
  )
}

useGLTF.preload('/ayed.glb')
