/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/combinedglb.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Torus.geometry}
        material={nodes.Torus.material}
        rotation={[0, -0.07, 0.15]}
        scale={[1, 1, 1.06]}
      />
      <mesh
        geometry={nodes.Torus001.geometry}
        material={nodes.Torus001.material}
        position={[0.53, 0.55, 0.51]}
        rotation={[2.58, 0, 0]}
        scale={[-1, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/combinedglb.glb')
