name: "Cache Omnid Data"
on:
  schedule:
    - cron: "0 0,12 * * *" # Every 12 hrs.
  workflow_dispatch:

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Cache Omnid Data
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pnpm install

    - name: Cache Omnid Data
      env:
        TEXTILE_THREADID: ${{ secrets.TEXTILE_THREADID }}
        TEXTILE_PK: ${{ secrets.TEXTILE_PK }}
        TEXTILE_HUB_KEY_DEV: ${{ secrets.TEXTILE_HUB_KEY_DEV }}
        PK_ORACLE: ${{ secrets.PK_ORACLE }}
        CNVSEC_ID: ${{ secrets.CNVSEC_ID }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
        BITQUERY_API_KEY: ${{ secrets.BITQUERY_API_KEY }}
      run: pnpm cron:cacheV2
