name: "Cache Omnid Data"
on:
  schedule:
    - cron: "0 0,12 * * *" # Every 12 hrs.

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Cache Omnid Data
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Cache Omnid Data
      env:
        TEXTILE_THREADID: ${{ secrets.TEXTILE_THREADID }}
        TEXTILE_PK: ${{ secrets.TEXTILE_PK }}
        TEXTILE_HUB_KEY_DEV: ${{ secrets.TEXTILE_HUB_KEY_DEV }}
        PK_ORACLE: ${{ secrets.PK_ORACLE }}
        CNVSEC_ID: ${{ secrets.CNVSEC_ID }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
        BITQUERY_API_KEY: ${{ secrets.BITQUERY_API_KEY }}
      run: yarn cron:cacheV2
